swagger: '2.0'
info:
  title: "Ecommerce API"
  description: "Brief description"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  bearerAuth: 
    type: apiKey
    name: Authorization
    in: header

paths:
  /customers/login:
    post: 
      tags:
        - Customer
      summary: "Login endpoint (generates a token)"
      description: "Endpoint for user authentication and token generation"
      security:
        - bearerAuth:
      parameters: 
        - in: "body"
          name: "body"
          description: "Credentials for login (email and password)"
          required: true
          schema:
            $ref: "#/definitions/LoginPayload"
      responses:
        200:
          description: "Login Successful"
          schema:
            $ref: "#/definitions/LoginResponse"
          examples:
            application/json:
              token: "adafiphwefanip3dkfapdif"
              message: "Successfully logged in"
              status: "success"

  /customers:
    get:
      tags:
        - Customer
      summary: "Retrieve a list of customer objects"
      description: "Endpoint to retrieve all customers, requires token authentication"
      security:
      responses:
        200:
          description: "Successfully retrieved all customers"
          schema:
            $ref: "#/definitions/GetCustomersResponse"
          examples:
            application/json:
              name: "Christy"
              email: "christy@gmail.com"
              phone: "98754431"
              username: "ChristyH"
              admin: 0

    post:
      tags:
        - Customer
      summary: "Create a customer object"
      description: "Endpoint to create a customer in the e-commerce system"
      parameters:
        - in: "body"
          name: "body"
          description: "Customer object"
          required: true
          schema:
            $ref: "#/definitions/CreateCustomerPayload"
      responses:
        200:
          description: "Customer created successfully"
          schema:
            $ref: "#/definitions/CreateCustomerResponse"
          examples:
            application/json:
              name: "Christy"
              email: "christy@gmail.com"
              phone: "98754431"
              username: "ChristyH"
              admin: 0

  /product:
    get:
      tags:
        - Product
      summary: "Retrieve a list of product objects"
      description: "Endpoint to retrieve all products"
      security:
      responses:
        200:
          description: "Successfully retrieved all products"
          schema:
            $ref: "#/definitions/GetProductsResponse"
          examples:
            application/json:
              id: 1
              price: 89.99
              product_name: "Cat Tower"

    post:
      tags:
        - Product
      summary: "Create a product object in our e-commerce system"
      description: "Endpoint to create a product object"
      security:
      parameters:
        - in: "body"
          name: "body"
          description: "Product object"
          required: true
          schema:
            $ref: "#/definitions/CreateProduct"
      responses:
        200:
          description: "Product created successfully"
          schema:
            $ref: "#/definitions/CreateProductResponse"
          examples:
            application/json:
              id: 1
              price: 89.99
              product_name: "Cat Tower"

  /orders:
    get:
      tags:
        - Order
      summary: "Retrieve a list of all orders"
      description: "Endpoint to view all orders"
      security:
      responses:
        200:
          description: "A list of orders with products"
          schema:
            $ref: '#/definitions/GetOrder'
          examples:
            application/json:
              customer_id: 2
              id: 5
              order_date: "2024-09-02"
              products:
                - id: 1
                  price: 89.99
                  product_name: "Cat Tower"
                - id: 2
                  price: 75.0
                  product_name: "Tall Lamp - 48in"

  /cart:
    post:
      tags:
        - Cart
      summary: "Add a product to the customer's cart"
      description: "Endpoint to add a product to the customer's cart"
      security:
        - bearerAuth:
      parameters:
        - in: "body"
          name: "body"
          description: "Cart object"
          required: true
          schema:
            $ref: "#/definitions/AddToCart"
      responses:
        200:
          description: "Products added to cart"
          schema:
            $ref: "#/definitions/AddToCartResponse"
          examples:
            application/json:
              message: "Products added to cart"

    delete:
      tags:
        - Cart
      summary: "Remove a product(s) from the customer's cart"
      description: "Endpoint to remove product(s) from the customer's cart"
      security:
        - bearerAuth: 
      responses:
        200:
          description: "Product removed from cart"
          schema:
            $ref: "#/definitions/RemoveItemFromCartResponse"
          examples:
            application/json:
              message: "Product removed from cart"

    get:
      tags:
        - Cart
      summary: "View all products in the customer's cart"
      description: "Endpoint to view all products in the customer's cart"
      security:
        - bearerAuth:
      responses:
        200:
          description: "Cart contents retrieved"
          schema:
            $ref: "#/definitions/ViewCartResponse"
          examples:
            application/json:
              customer_id: 2
              products:
                - id: 1
                  price: 89.99
                  product_name: "Cat Tower"
                - id: 2
                  price: 75.0
                  product_name: "Tall Lamp - 48in"

  /cart/empty-cart:
    delete:
      tags:
        - Cart
      summary: "Remove all products from the customer's cart"
      description: "Endpoint to empty the customer's cart"
      security:
        - bearerAuth:
      responses:
        200:
          description: "Cart has been emptied"
          schema:
            $ref: "#/definitions/EmptyCartResponse"
          examples:
            application/json:
              message: "Cart has been emptied"

  /cart/place-order:
    post:
      tags:
        - Cart
      summary: "Place an order with the products in the customer's cart"
      description: "Endpoint to place an order with the products in the customer's cart"
      security:
        - bearerAuth:
      responses:
        200:
          description: "Order placed successfully"
          schema:
            $ref: "#/definitions/PlaceOrderResponse"
          examples:
            application/json:
              message: "Order placed successfully"
              order_date: "Tue, 10 Sep 2024 00:00:00 GMT"
              order_id: 13

#===================Definitions===========#

definitions:
  LoginPayload:
    type: "object"
    properties: 
      email:
        type: "string"
        description: "Email"
      password:
        type: "string"
        description: "Password"
    required:
      - email
      - password
  
  LoginResponse:
    type: "object"
    properties:
      token:
        type: "string"
        description: "Authentication token on successful login"
      message: 
        type: "string"
        description: "Message indicating success or failure"
      status: 
        type: "string"
        description: "Status of operation"
    required:
      - message
      - status

  GetCustomersResponse:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Hiro Celsius"
      phone:
        type: "string"
        example: "555-555-5555"
      email:
        type: "string"
        example: "hiro@gmail.com"
      username:
        type: "string"
        example: "hiroc"
      admin:
        type: "integer"
        example: "0"

  CreateCustomerPayload:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Christy Hernandez"
      phone:
        type: "string"
        example: "111-111-1111"
      email:
        type: "string"
        example: "christy@yahoo.com"
      password:
        type: "string"
        example: "13579"
      username:
        type: "string"
        example: "christyh"
      admin:
        type: "integer"
        example: "1"
    required:
      - name
      - phone
      - email
      - password
      - username
      - admin

  CreateCustomerResponse:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Hiro Celsius"
      phone:
        type: "string"
        example: "555-555-5555"
      email:
        type: "string"
        example: "hiro@gmail.com"
      password:
        type: "string"
        example: "pythonrocks"
      username:
        type: "string"
        description: "hiroc"
      admin:
        type: "integer"
        description: "0"


  GetProductsReponse:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "Product ID"
      price:
        type: "number"
        format: "float"
        description: "Price of the product"
      product_name:
        type: "string"
        description: "Name of the product"

  CreateProductPayload:
    type: "object"
    properties:
      price:
        type: "number"
        format: "float"
        description: "Price of the product"
      product_name:
        type: "string"
        example: "iPhone 14 Pro"
    required:
      - price
      - product_name
  

  CreateProductResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        example: "3"
      price:
        type: "number"
        format: "float"
        example: "950"
      product_name:
        type: "string"
        example: "iPhone 14 Pro"

  GetOrderResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "Order ID"
      customer_id:
        type: "integer"
        description: "ID of the customer"
      order_date:
        type: "date"
        description: "Date and time when the order was placed"
      products:
        type: "array"
        description: "List of products in the order"
        items:
          type: "object"
          properties:
            id:
              type: "integer"
              description: "Product ID"
            product_name:
              type: "string"
              description: "Name of the product"
            price:
              type: "float"
              description: "Product price"

  AddToCartPayload:
    type: "object"
    properties:
      customer_id:
        type: "integer"
        example: "1"
      product_ids:
        type: "list"
        example: "[1, 2, 3]"
    required:
      - customer_id
      - product_ids

  AddToCartResponse:
    type: "object"
    properties:
      message:
        type: "string"
        description: "products added to cart"

  RemoveItemFromCartPayload:
    type: "object"
    properties:
      customer_id:
        type: "integer"
        example: "1"
      product_ids:
        type: "list"
        example: "[1, 2, 3]"
    required:
      - customer_id
      - product_ids


  RemoveItemFromCartResponse:
    type: "object"
    properties:
      message:
        type: "string"
        description: "Product removed from cart"

  ViewCartResponse:
    type: "object"
    properties:
      customer_id:
        type: "integer"
        description: "ID of the customer"
      products:
        type: "array"
        items:
          type: "object"
          properties:
            id:
              type: "integer"
              description: "Product ID"
            price:
              type: "number"
              format: "float"
              description: "Product price"
            product_name:
              type: "string"
              description: "Name of the product"

  EmptyCartReponse:
    type: "object"
    properties:
      message:
        type: "string"
        example: "cart has been emptied"

  PlaceOrderResponse:
    type: "object"
    properties:
      message:
        type: "string"
        example: "Order placed succesfully"
      order_date:
        type: "date"
        example: "Tue, 10 Sep 2024 00:00:00 GMT"
      order_id:
        type: "integer"
        example: "13"

